# -*- coding: utf-8 -*-
"""AIML.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13ccEsVfUm3K-T93pIiXZNOqCdJNR3Gsl
"""

import pandas as pd
from sklearn.tree import DecisionTreeClassifier
import joblib

# Load and train the model (done automatically)
data = pd.read_csv("datatraining.txt")

X = data[['Temperature','Humidity','Light','CO2']]
y = data['Occupancy']

model = DecisionTreeClassifier()
model.fit(X, y)

print("\nSMART ROOM OCCUPANCY SYSTEM")
print("--------------------------------")

temp = float(input("Enter Temperature: "))
hum = float(input("Enter Humidity: "))
light = float(input("Enter Light Level: "))
co2 = float(input("Enter CO2 Level: "))

prediction = model.predict([[temp, hum, light, co2]])

print("\nRESULT:")
if prediction[0] == 1:
    print("✅ Room is OCCUPIED")
else:
    print("❌ Room is NOT OCCUPIED")